---
title: "Canopy Over Time"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(here)
library(purrr)
library(tidyr)
library(broom)
library(DT)
library(ggrepel)
source(here("scripts/branding.R"))
load(here("data/complete_canopy_2022.RData"))
canopy_old = readRDS(here("data/canopy-2019-2021.rds"))

xwalk = read_csv(here("data/Tags-SY2021-22 Tags.csv"), show_col_types = FALSE) %>%
  select(tag = `Variable name`, tag_20_21 = `2020-21 equivalent`, tag_18_19 = `2018-19 equivalent`)
```

## All Schools

First, a look at all the Canopy schools in all years.

```{r}
## Notes 5 May 2022:
## DONE: make sure 2020 schools are not duplicated--they were not duplicated
## DONE: re-run with only schools that participated in last 2 years--added new section
## DONE: within schools that participated multiple years, look at tag additions and subtractions
all_tags = unique(na.omit(unlist(xwalk)))

canopy_old = canopy_old %>%
  mutate(expanded_success = coalesce(expanded_success, redefining_success)) %>%
  select(-redefining_success)

rn_20_21 = which(xwalk$tag_20_21 %in% names(canopy_old))

canopy_old = canopy_old %>%
  select(year, school_id, any_of(all_tags)) %>%
  rename(setNames(xwalk[["tag_20_21"]][rn_20_21], xwalk[["tag"]][rn_20_21]))

rn_18_19 = which(xwalk$tag_18_19 %in% names(canopy_old))


canopy_old = canopy_old %>%
  rename(setNames(xwalk[["tag_18_19"]][rn_18_19], xwalk[["tag"]][rn_18_19]))

canopy_old = canopy_old %>% mutate(across(everything(), as.character))

over_time = practices_data %>%
  mutate(year = "2022", school_id = as.character(school_id)) %>%
  select(school_id, year, any_of(all_tags)) %>%
  mutate(across(everything(), as.character)) %>%
  bind_rows(canopy_old)

sy_all = c("18-19", "19-20", "20-21", "21-22")
over_time %>%
  mutate(
    sy = case_when(
      year == "2019" ~ "18-19",
      year %in% c("2020", "2021") ~ "20-21",
      year == "2022" ~ "21-22"
    ),
    sy = factor(sy, levels = sy_all),
    sy_i = as.integer(sy) - 1
    # setting levels here accounts for the missing school year in the spacing.
  ) -> over_time

if((over_time %>% 
  group_by(school_id, sy) %>%
  filter(n() > 1) %>%
  nrow) > 0) stop("duplicates introduced!")

over_time %>%
  pivot_longer(cols = starts_with("practice"), names_to = "tag") %>%
  mutate(flag = case_when(is.na(value) | value == "0" ~ 0L, TRUE ~ 1L)) %>%
  group_by(sy) %>%
  mutate(n_sch_year = n_distinct(school_id)) %>%
  group_by(sy, sy_i, tag) %>%
  summarize(pct_practicing = mean(flag), n_sch_year = first(n_sch_year), .groups = "drop") %>%
  filter(pct_practicing > 0) ->
  long
```


```{r, echo = FALSE}
ggplot(long, aes(x = sy, y = pct_practicing, group = tag)) +
  geom_line(alpha = 0.6, color = transcend_cols["teal"], size = 0.3) +
  geom_point(alpha = 0.9, color = transcend_cols["teal"], size = 1.2) +
  bar_y_scale_percent +
  scale_x_discrete(drop = FALSE) +
  labs(
    y = "Percent of schools identifying practice",
    x = "Canopy survey school year",
    title = "Changes in practices over time"
  )
```

```{r, fig.height=10, fig.width = 9, echo = FALSE}
long %>% 
  group_by(tag) %>%
  nest() %>%
  mutate(
    models = lapply(data, \(df) tidy(lm(pct_practicing ~ sy_i, data = df, weights = n_sch_year)))
  ) -> mods 

mods %>%
  unnest(models) %>%
  filter(term == "sy_i") ->
  coefs

coefs %>%
  ungroup %>%
  filter(!is.na(estimate)) %>%
  mutate(rank = rank((-estimate))) %>%
  arrange(rank) %>%
  mutate(tag = reorder(factor(tag), estimate)) -> coefs
```

```{r, fig.height=10, fig.width = 9, echo = FALSE}
ggplot(coefs, aes(y = tag, x = estimate)) +
  geom_point(aes(color = rank), size = 3) +
  scale_color_continuous(guide = "none", trans = "reverse") +
  scale_y_discrete(labels = label_tags) +
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(
    x = "Percentage point change\nin schools selecting practices",
    y = "",
    title = "Average change in tagging patterns"
  ) +
  theme(axis.text.y = element_text(size = rel(0.5)))
```

```{r slice_top, fig.width = 9, include = FALSE}
coefs %>% slice(1:15) %>%
  ggplot(aes(y = tag, x = estimate)) +
  geom_point(aes(color = rank), size = 3) +
  scale_color_continuous(guide = "none", trans = "reverse") +
  scale_y_discrete(labels = label_tags) +
  scale_x_continuous(labels = scales::label_percent(accuracy = 1), limits = c(0, .25), expand = expansion()) +
  labs(
    x = "Average Annual Percentage point change\nin schools selecting practices",
    y = "",
    title = "Average change in tagging patterns"
  ) +
  theme(axis.text.y = element_text(size = rel(0.5)))
```


```{r, include = FALSE}
coefs %>% 
  arrange(rank) %>%
  slice(1:20) %>%
  unnest(data) %>%
  select(-sy_i, -term, -statistic) %>%
  datatable(
    caption = "Percentage change in practice representation among all Canopy schools"
  ) %>%
  formatRound(digits = 3,columns = c("estimate", "std.error", "p.value")) %>%
  formatPercentage(columns = "pct_practicing", digits = 1)
```

## Repeat Schools

Now looking at only schools that responded in 2022 as well as in a previous 
survey round.

```{r repeat_schools, fig.height=11, fig.width= 9}
repeat_schools = over_time %>%
  group_by(school_id) %>%
  filter(n_distinct(sy) > 1 & "21-22" %in% sy) %>%
  pull(school_id)

over_time %>%
  filter(school_id %in% repeat_schools) %>%
  pivot_longer(cols = starts_with("practice"), names_to = "tag") %>%
  mutate(flag = case_when(is.na(value) | value == "0" ~ 0L, TRUE ~ 1L)) %>%
  group_by(sy) %>%
  mutate(n_sch_year = n_distinct(school_id)) %>%
  group_by(sy, sy_i, tag) %>%
  summarize(pct_practicing = mean(flag), n_sch_year = first(n_sch_year), .groups = "drop") %>%
  filter(pct_practicing > 0) ->
  long_rpt

long_rpt %>% 
  group_by(tag) %>%
  nest() %>%
  mutate(
    models = lapply(data, \(df) tidy(lm(pct_practicing ~ sy_i, data = df, weights = n_sch_year)))
  ) -> mods_rpt
## TODO redo model weighting by n_sch_yr
## Also 2019 is 2018-2019, 2020 and 2021 are 2020-2021, and 2022 is 2021-2022
mods_rpt %>%
  unnest(models) %>%
  filter(term == "sy_i") ->
  coefs_rpt

coefs_rpt %>%
  ungroup %>%
  filter(!is.na(estimate)) %>%
  mutate(rank = rank(-abs(estimate))) %>%
  arrange(rank) %>%
  mutate(tag = reorder(factor(tag), estimate)) -> coefs_rpt

ggplot(coefs_rpt, aes(y = tag, x = estimate)) +
  geom_point(aes(color = rank), size = 3) +
  scale_color_continuous(guide = "none", trans = "reverse") +
  scale_y_discrete(labels = label_tags) +
  scale_x_continuous(labels = scales::label_percent(accuracy = 1)) +
  labs(
    x = "Percentage point change\nin schools selecting practices",
    y = "",
    title = "Average annual change in tagging patterns",
    subtitle = "For schools in Canopy 2022 as well as a previous year"
  ) +
  theme(
    axis.text.y = element_text(size = rel(0.5)),
    plot.subtitle = element_text(size = rel(0.8))
  )

```
```{r, fig.width = 9, fig.height = 8}
coefs_rpt %>% 
    slice_max(estimate, n = 20) %>%
  ggplot(aes(y = tag, x = estimate)) +
  geom_point(aes(color = rank), size = 3) +
  scale_color_continuous(guide = "none", trans = "reverse") +
  scale_y_discrete(labels = label_tags) +
  scale_x_continuous(
    labels = scales::label_percent(accuracy = 1),
    limits = c(0, 0.25), expand = expansion()
  ) +
  labs(
    x = "Average annual percentage point change\nin schools selecting practices",
    y = "",
    title = "Top 20 tags by average annual growth",
    subtitle = "For schools in Canopy 2022 as well as a previous year"
  ) +
  theme(
    axis.text.y = element_text(size = rel(0.7)),
    plot.subtitle = element_text(size = rel(0.8))
  )
```

```{r}
coefs_rpt %>% 
  arrange(rank) %>%
  #slice(1:20) %>%
  unnest(data) %>%
  select(-sy_i, -term, -statistic) %>%
  datatable(
    caption = "Percentage change in practice representation among 2022 Canopy schools with previous responses"
  ) %>%
  formatRound(digits = 3,columns = c("p.value")) %>%
  formatPercentage(columns = c("pct_practicing", "estimate", "std.error"), digits = 1)
```

### Call-out practices

```{r, fig.width=10, fig.height = 7}
hilight = paste0(
  "practices_", 
  c("trauma_informed",
    "culturally_responsive",
    "sel_integrated",
    "sel_curriculum",
    "competency_framework", 
    "competency_education"
    ))
coefs_rpt %>% 
  filter(
    tag %in% hilight
  ) %>%
  unnest(data) -> hilight_data

hilight_data |>
  filter(sy_i == 3) -> hilight_labs

ggplot(hilight_data, 
       aes(x = sy, y = pct_practicing, color = tag, group = tag)) +
  geom_point(size = 3, alpha = 0.8) +
  geom_line(
    stat = "smooth", 
    method = "lm", 
    se = FALSE, 
    formula = y ~ x,
    size = 1,
    alpha = 0.7
  ) +
  geom_text_repel(
    data = hilight_labs, 
    aes(
      label = paste(
        label_tags(tag),
        "\nslope =", 
        scales::percent_format(accuracy = 0.1)(estimate),
        "points per year"
      )
    ),
    hjust = 0,
    nudge_x = 0.11,
    size = 3.5,
    direction = "y",
    xlim = c(-100, 100)
  ) + 
  coord_cartesian(clip = "off") + 
  scale_color_manual(
    labels = label_tags, 
    values = c(transcend_cols[1:3] |> unname(), transcend_cols2[c(1, 2, 4)])
  ) +
  scale_y_continuous(
    labels = scales::label_percent(accuracy = 1),
    limits = c(0, 1), expand = expansion()
  ) +
  scale_x_discrete(
    expand = expansion(add = c(0.05)),
    drop = FALSE
  ) +
  guides(color = "none") +
  labs(
    x = "School year",
    y = "Schools indicating practice",
    color = "",
    title = "Increasing adoption of selected practices",
    subtitle = "For schools in Canopy 2022 as well as a previous year"
  ) +
  theme(
   # axis.text.y = element_text(size = rel(0.7))
    panel.grid.major.x = element_blank(),
    plot.margin = margin(.35, 8, .35, .35, "cm")
  )
```

It would be easy to make versions of this graph with other selected practices.

## Tags added and subtracted by schools over time


```{r, fig.height= 18, fig.width = 22}
over_time %>%
  group_by(school_id) %>%
  filter(n_distinct(year) > 1 & "2022" %in% year) %>%
  arrange(desc(year)) %>%
  slice(1:2) %>% ## last 2 observations for each 2022 repeat school
  ungroup %>%
  pivot_longer(cols = starts_with("practice"), names_to = "tag") %>%
  mutate(flag = case_when(is.na(value) | value == "0" ~ 0L, TRUE ~ 1L)) %>%
  group_by(school_id, tag) %>%
  arrange(desc(year)) %>%
  summarize(
    change = case_when(
      all(value == 0) ~ NA_character_,
      all(value == 1) ~ "Kept",
      value[1] == 0 & value[2] == 1 ~ "Added",
      value[2] == 1 & value[1] == 0 ~ "Retired",
      TRUE ~ NA_character_
    ), .groups = "drop"
  ) %>% 
  filter(tag %in% coefs_rpt$tag) %>%
  mutate(change_score = case_when(
    change == "Kept" ~ 1L,
    change %in% c("Added", "Retired") ~ 3L,
    TRUE ~ 0L
  )) %>%
  mutate(school_id = reorder(school_id, -change_score, FUN = sum)) %>%
  left_join(coefs_rpt %>% select(tag, rank), by = "tag") %>%
  mutate(tag = reorder(tag, rank)) ->
  tag_changes

ggplot(tag_changes, aes(x = school_id, y = tag, fill = change)) +
  geom_tile() + 
  labs(
    x = "School (sorted by number of practices added/identified",
    y = "Practice (sorted according to the table above)",
    title = "Practices added, kept, and retired by repeat Canopy schools in their most recent 2 responses",
    subtitle = 
"There are no red squares: no 2022 Canopy school indicated they retired a practice
compared to their previous Canopy response.",
    fill = "Action"
  ) +
  scale_fill_manual(
    values = c(
      Kept = transcend_cols_noname("teal"),
      Added = transcend_cols_noname("blue"),
      Retired = transcend_cols_noname("red")
    ),
    na.value = transcend_grays[3]
  ) +
  scale_y_discrete(
    labels = label_tags
  ) +
  coord_equal() +
  theme_transcend_sparse +
  theme(axis.text.x = element_blank(), axis.ticks.x = element_blank())
  
```


