---
title: "Leaps Analysis"
author: "Janette Avelar"
date: '2022-07-25'
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(rio)
library(psych)
library(tidyverse)
library(ggplot2)
library(DT)
library(scales)
library(rstanarm)
library(broom.mixed)
library(gmodels)
source(here("scripts", "branding.R")) #, local = knitr::knit_global()
load(here("data", "complete_canopy_2022.RData"))
```

# Simple Descriptives  

```{r desc}
leaps_desc <- clean_data_full %>% 
  select(starts_with("leaps_"), school_name, confidential_leader_race, confidential_leader_gender, confidential_leadership_team_diversity, confidential_teaching_staff_diversity, ends_with("_percent"), -starts_with("leaps_rank_")) %>% 
  mutate_at(vars(starts_with("leaps")), str_replace, case_when, "0" ~ "no",
            TRUE ~ "yes")

#create vector of leaps labels
leaps_labs <- 
```


## Demographic distribution of Leaps  

# Correlations  

## Correlation with Type  

## Correlation with Locale  

# Models

## Race and SES  

## Controlling for Aggregate non-White population  

## Interaction between locale and type  