---
title: "Demographics in Canopy Schools"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)
library(here)
library(purrr)
library(tidyr)
source(here("scripts/branding.R"))
load(here("data/complete_canopy_2022.RData"))
```

```{r, echo = TRUE}
demographic_data %>%
  count(lead = confidential_leadership_team_diversity, staff = confidential_teaching_staff_diversity) %>%
  ggplot(aes(x = staff, y = lead)) +
  geom_tile(aes(fill = n)) +
  geom_label(aes(label = n)) +
  labs(x = "Staff", y = "Leadership", title = "Staff diversity") +
  scale_fill_continuous(guide = "none") +
  theme_transcend_sparse +
  theme(axis.text.x = element_text(angle = 35, hjust = 1, vjust = 1))
```

```{r, include=FALSE}
demo = demographic_data %>%
  mutate(across(contains("percent"), \(x) {
    x = suppressWarnings(as.numeric(x))
    if(max(x, na.rm = TRUE) > 1) {x = x / 100}
    return(x)
  }))

demo_long = demo %>%
  pivot_longer(contains("percent"), names_to = "dem", values_to = "value") %>%
  select(school_id, dem, value) %>%
  mutate(labels = label_dems(dem)) %>%
  mutate(    labels = factor(labels, levels = c(
      "% Native American and\nAlaskan Native students", 
      "% Asian students", 
      "% Black students",
      "% Hispanic students", 
      "% Native Hawaiian and\nPacific Islander students", 
      "% Multiracial students", 
      "% White students",
      "% English Language Learners", 
      "% FRPL eligible",
      "% Students with Disabilities"
    ))
  )
```

```{r, fig.height=10, echo = TRUE}
ggplot(demo_long, aes(y = value, x = factor(1))) +
  geom_violin(
    fill = transcend_cols["teal"],
    scale = "area",
    adjust = 0.8
  ) +
  geom_point(
    color = transcend_cols["red"],
    position = position_jitter(width = 0.2),
    size = 0.2
  ) +
  facet_wrap(vars(labels), nrow = 2) +
  bar_y_scale_percent +
  labs(
    x = "", y = "", 
    title = "Student diversity in Canopy schools",
    subtitle = "Width indicates the number of Canopy schools\nwith demographics of a certain percentage"
  ) +
  theme(
    axis.text.x = element_blank(),
    strip.text = element_text(size = rel(0.5)),
    plot.subtitle = element_text(size = rel(0.7))
  )
```


```{r, fig.height = 6, fig.width = 7, echo = TRUE}
#NOTE: modified by Janette 8/15 for Fig 3 final version
fig3 <- demo_long %>% 
  mutate(labels = recode_factor(labels,
                    "% Native American and\nAlaskan Native students" = "American and\nAlaska Native students",
                    "% Asian students" = "Asian students",
                    "% Black students" = "Black students",
                    "% Hispanic students" = "Hispanic or Latina/o/x students",
                    "% Native Hawaiian and\nPacific Islander students" = "Native Hawaiian and\nPacific Islander students",
                    "% Multiracial students" = "Multiracial students",
                    "% White students" = "White students",
                    "% English Language Learners" = "Students classified as\nEnglish language learners",
                    "% FRPL eligible" = "Students eligible for\nfree/reduced-price lunch",
                    "% Students with Disabilities" = "Students with Disabilities"),
         labels = replace_na(labels, "Students classified as\nEnglish learners"))

fig3_plot <-
ggplot(fig3, aes(x = value, y = labels)) +
  # geom_violin(
  #   fill = transcend_cols["teal"],
  #   scale = "area",
  #   adjust = 0.8
  # ) +
  geom_point(
    color = transcend_cols["teal"],
    position = position_jitter(height = 0.2),
    size = 0.8
  ) +
  bar_x_scale_percent +
  scale_y_discrete(breaks = (levels(fig3$labels))) +
  labs(
    x = "Percentage of students in each school", 
    y = "", 
    title = "Distribution of Canopy schools\nby student demographic categories",
    subtitle = "A dot represents one Canopy learning environment in each demographic category"
  ) +
  theme(
    axis.text.y = element_text(size = rel(0.7)),
    axis.text.x = element_text(size = rel(0.7), hjust = 0.7),
    #strip.text = element_text(size = rel(0.5)),
    plot.subtitle = element_text(size = rel(0.7))
  )
# save plot
ggsave_transcend(fig3_plot, file = "figure 3", fig_height = 9, fig_width = 9)  
```

```{r, fig.height=9, fig.width = 12, echo = TRUE}
brk = seq(0, 1, by = 0.1)
demo_long %>%
  mutate(
    bin = cut(
      value,
      breaks = brk,
      labels = sprintf("%s-%s", scales::percent(head(brk, -1)), scales::percent(tail(brk, -1))),
      include.lowest = TRUE
    )
  ) %>%
  count(dem, labels, bin) %>%
ggplot(aes(y = bin, x = n)) +
  geom_col(aes(fill = is.na(bin)), width = 0.8) +
  facet_wrap(vars(labels), nrow = 2) +
  # scale_x_continuous(
  #   labels = scales::comma_format(accuracy = 1),
  #   expand = expansion(mult = c(0, 0.1)),
  #   breaks = seq(40, 160, by = 40)
  # ) +
  bar_x_scale_count +
  scale_fill_manual(
    values = unname(c(transcend_cols["teal"], transcend_grays[2]))
  ) +
  guides(fill = "none") +
  labs(
    x = "Number of Canopy schools", y = "", 
    title = "Student diversity in Canopy schools",
    subtitle = "Number of Canopy schools with various demographic characteristics"
  ) +
  theme(
   strip.text = element_text(size = rel(0.6), vjust = 0),
   plot.subtitle = element_text(size = rel(0.8)),
   axis.text = element_text(size = rel(0.6)),
   panel.grid.major.y = element_blank()
  )

```



